"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ConsolePro_1 = require("../ConsolePro");
// @ts-ignore
var index_js_1 = require("../index.js");
console.log('-------------------------------- PROBANDO EL CÓDIGO --------------------------------');
console.log('-------------------------------- Console Instance --------------------------------');
var logger = new ConsolePro_1.ConsolePro();
logger.log('Hola mundo', 'd');
logger.log('Hola mundo', 'D');
logger.log('Hola mundo', 'i');
logger.log('Hola mundo', 'w');
logger.log('Hola mundo', 's');
logger.log('Hola mundo', 'e');
logger.log('Hola mundo');
var loggerTwo = new ConsolePro_1.ConsolePro('./log.log');
loggerTwo.log('Hola', 's');
loggerTwo.log('Hola', 'w');
loggerTwo.log('Hola', 'i');
loggerTwo.log('Hola', 'I');
loggerTwo.log('Hola', 'I');
loggerTwo.log('Hola', 'I');
loggerTwo.log('Hola', 'E');
loggerTwo.log('Hola', 'd');
loggerTwo.log('Hola', 'd');
loggerTwo.log('Hola', 'd');
loggerTwo.log('Hola', 'd');
loggerTwo.log('Hola');
console.log('-------------------------------- Console Static --------------------------------');
ConsolePro_1.ConsolePro.log('Hola mundo', 'd');
ConsolePro_1.ConsolePro.log('Hola mundo', 'D');
ConsolePro_1.ConsolePro.log('Hola mundo', 'i');
ConsolePro_1.ConsolePro.log('Hola mundo', 'w');
ConsolePro_1.ConsolePro.log('Hola mundo', 's');
ConsolePro_1.ConsolePro.log('Hola mundo', 'e');
ConsolePro_1.ConsolePro.log('Hola mundo');
console.log('-------------------------------- PROBANDO EL EXPORT --------------------------------');
index_js_1.ProLogJs.log('Hola', 's');
//# sourceMappingURL=Test.js.map